language: python
python: 3.7
dist: xenial
sudo: required
services:
  - docker
install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile
stage: run tests
script:
  - pipenv run coverage
  - codecov
after_success:
  - bash ./scripts/docker_push.sh
